### ISSUE TITLE
Turn the "hype" into each section's header

### ISSUE THREAD

**Issue by chelmertz** [hwayne/awesome-cold-showers#11]
This is just food for thought, sorry for creating an issue.

When reading the formatted markdown, the headers stick out. Since the headers are 1:1 to papers' names, they may not be "the" obvious representation of the hype.

There's also no room in the current format for associating multiple papers (with different approaches) to the single hype, if that's something that would be useful. I.e. possibly multiple sets of {shower,caveat,paper} per hype.

**Comment by hwayne** [comment]
> This is just food for thought, sorry for creating an issue.

Never apologize for constructive contributions 👍 

> When reading the formatted markdown, the headers stick out. Since the headers are 1:1 to papers' names, they may not be "the" obvious representation of the hype. There's also no room in the current format for associating multiple papers (with different approaches) to the single hype.

That's a really good point. I think that as the list expands we'll need to start putting things in sections so it's clear what they takedown. In my opinion we should wait for more articles/videos/blogposts so we have a better sense of how to break it down. What do you think?

**Comment by chelmertz** [comment]
>[...] we should wait for more articles/videos/blogposts [...]

Sounds like a plan! The README is probably easy enough to glance over completely for new users, and the changelog is good enough for new edits. When the information grows though.. it's not a database :)
