### ISSUE TITLE
Why Do Keynote Speakers Keep Suggesting That Improving Security Is Possible?

### ISSUE THREAD

**Issue by pbrkr** [hwayne/awesome-cold-showers#19]
This seems perfect to add to the list:

Q: Why Do Keynote Speakers Keep Suggesting That Improving Security Is Possible?
A: Because Keynote Speakers Make Bad Life Decisions and Are Poor Role Models

https://www.youtube.com/watch?v=ajGX7odA87k

It's an excellent cold shower on the promises of generalised AI and Machine Learning and how they should not be let anywhere near either the internet or critical infrastructure, let alone both. It's also hilarious and really accessible.

**Comment by hwayne** [comment]
I love love _love_ Mickens' talks but they're not rigorous sources, as per the [contribution guidelines](https://github.com/hwayne/awesome-cold-showers/blob/master/CONTRIBUTING.md).
