### ISSUE TITLE
a bunch of cold showers found in one place

### ISSUE THREAD

**Issue by bonds** [hwayne/awesome-cold-showers#2]
This book starts with guidance on how to be critical of software productivity research, and then goes on to present a bunch of studies where folks have tried to prove or disprove the benefits of different productivity enhancing ideas:

http://shop.oreilly.com/product/9780596808303.do

**Comment by hwayne** [comment]
I love that book so much. It's probably one of the most influential books on my development as a programmer and I try to reread it roughly once a year. At the bare minimum "Architecting: How Much and When", "Pair Programming", and "How effective is test-driven development" belong on here, and you can make strong case for half of the rest.* It's mostly a matter of tracking down free versions, maybe on author pages or some preprints.

I'm also going to fiat that anything from _Making Software_ should have the following note, in addition to any other notes:

```
Originally from [Making Software](http://shop.oreilly.com/product/9780596808303.do).
```
* The other half are solid papers but not cold showers, IMO.
