### ISSUE TITLE
Ontologies

### ISSUE THREAD

**Issue by vinipsmaker** [hwayne/awesome-cold-showers#21]
Fortunately it's not mainstream (so not hype?), but the amount of money that goes into teams to foster this initiative is not something to ignore.

https://people.well.com/user/doctorow/metacrap.htm

I won't write a PR, so this issue is just to drop a link in case someone steps up to do it.

**Comment by hwayne** [comment]
Things that aren't mainstream are totally kosher. I mean, I included a bunch of stuff on formal verification, and that's not exactly mainstream either. But this doesn't pass the [guidelines](https://github.com/hwayne/awesome-cold-showers/blob/master/CONTRIBUTING.md) on rigor or tactfulness. I do think a resource on ontologies would be valuable here; as you say, there's a lot of money in it.
