### ISSUE TITLE
Find "Maintaining Mental Models"

### ISSUE THREAD

**Issue by hwayne** [hwayne/awesome-cold-showers#7]
> "LATOZA, T. D., VENOLIA, G., AND DELINE, R. 2006.Maintaining mental models: a study of developer work habits. In Proc. of International Conference on Software Engineering. ACM, 492–501."

Found it as a cite in a different article, might potentially be a cold shower on documentation hype? Haven't looked to see if it's freely accessible.

**Comment by hwayne** [comment]
Couple more, _really_ need to find a better way to record these

> ROMANO, S., FUCCI, D., SCANNIELLO, G., TURHAN, B., AND JURISTO, N. 2016. Results from an ethnographically-informed study in the context of test driven development. In Proc. of the International Conference on Evaluation and Assessment in Software Engineering. ACM, New York, NY, USA, 10:1– 
>10:10. ROMANO, S., FUCCI, D., SCANNIELLO, G., TURHAN, B., AND JURISTO, N. 2017. Findings from a multimethod study on test-driven development. Information and Software Technology, –.

**Comment by adolfosilva** [comment]
Here are two of those three articles:

["Maintaining mental models: a study of developer work habits"](https://cs.gmu.edu/~tlatoza/papers/icse2006.pdf)
["Results from an ethnographically-informed study in the context of test driven development"](http://bura.brunel.ac.uk/bitstream/2438/14621/1/FullText.pdf)

**Comment by hwayne** [comment]
Hot damn thank you for the finds! Gonna be doing some reading tonight :D
